  (:goal
    (and
      (communicated_soil_data waypoint9)
      (communicated_soil_data waypoint1)
      (communicated_soil_data waypoint54)
      (communicated_soil_data waypoint28)
      (communicated_soil_data waypoint31)
      (communicated_soil_data waypoint81)
      (communicated_soil_data waypoint103)
      (communicated_soil_data waypoint97)
      (communicated_soil_data waypoint59)
      (communicated_soil_data waypoint14)
      (communicated_soil_data waypoint61)
      (communicated_soil_data waypoint63)
      (communicated_soil_data waypoint6)
      (communicated_soil_data waypoint40)
      (communicated_soil_data waypoint45)
      (communicated_soil_data waypoint53)
      (communicated_soil_data waypoint27)
      (communicated_soil_data waypoint87)
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint69)
      (communicated_soil_data waypoint20)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint82)
      (communicated_soil_data waypoint35)
      (communicated_soil_data waypoint80)
      (communicated_soil_data waypoint66)
      (communicated_soil_data waypoint76)
      (communicated_soil_data waypoint70)
      (communicated_soil_data waypoint71)
      (communicated_soil_data waypoint57)
      (communicated_soil_data waypoint74)
      (communicated_soil_data waypoint15)
      (communicated_soil_data waypoint17)
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint42)
      (communicated_soil_data waypoint65)
      (communicated_soil_data waypoint55)
      (communicated_soil_data waypoint58)
      (communicated_soil_data waypoint32)
      (communicated_soil_data waypoint102)
      (communicated_soil_data waypoint3)
      (communicated_soil_data waypoint36)
      (communicated_soil_data waypoint24)
      (communicated_soil_data waypoint96)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint41)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint8)
      (communicated_soil_data waypoint73)
      (communicated_soil_data waypoint10)
      (communicated_soil_data waypoint16)
      (communicated_soil_data waypoint50)
      (communicated_soil_data waypoint100)
      (communicated_soil_data waypoint30)
      (communicated_soil_data waypoint33)
      (communicated_rock_data waypoint26)
      (communicated_rock_data waypoint60)
      (communicated_rock_data waypoint67)
      (communicated_rock_data waypoint22)
      (communicated_rock_data waypoint45)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint72)
      (communicated_rock_data waypoint76)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint103)
      (communicated_rock_data waypoint16)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint27)
      (communicated_rock_data waypoint82)
      (communicated_rock_data waypoint41)
      (communicated_rock_data waypoint50)
      (communicated_rock_data waypoint65)
      (communicated_rock_data waypoint99)
      (communicated_rock_data waypoint11)
      (communicated_rock_data waypoint94)
      (communicated_rock_data waypoint63)
      (communicated_rock_data waypoint48)
      (communicated_rock_data waypoint25)
      (communicated_rock_data waypoint6)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint1)
      (communicated_rock_data waypoint2)
      (communicated_rock_data waypoint96)
      (communicated_rock_data waypoint74)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint101)
      (communicated_rock_data waypoint75)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint89)
      (communicated_rock_data waypoint29)
      (communicated_rock_data waypoint47)
      (communicated_rock_data waypoint52)
      (communicated_rock_data waypoint85)
      (communicated_rock_data waypoint93)
      (communicated_rock_data waypoint8)
      (communicated_rock_data waypoint98)
      (communicated_rock_data waypoint51)
      (communicated_rock_data waypoint32)
      (communicated_rock_data waypoint14)
      (communicated_rock_data waypoint43)
      (communicated_rock_data waypoint61)
      (communicated_rock_data waypoint69)
      (communicated_rock_data waypoint46)
      (communicated_image_data objective12 colour)
      (communicated_image_data objective22 colour)
      (communicated_image_data objective54 high_res)
      (communicated_image_data objective51 colour)
      (communicated_image_data objective35 colour)
      (communicated_image_data objective47 colour)
      (communicated_image_data objective42 colour)
      (communicated_image_data objective26 high_res)
      (communicated_image_data objective22 high_res)
      (communicated_image_data objective35 low_res)
      (communicated_image_data objective20 high_res)
      (communicated_image_data objective10 colour)
      (communicated_image_data objective48 colour)
      (communicated_image_data objective15 colour)
      (communicated_image_data objective40 colour)
      (communicated_image_data objective16 high_res)
      (communicated_image_data objective3 colour)
      (communicated_image_data objective1 colour)
      (communicated_image_data objective16 low_res)
      (communicated_image_data objective21 colour)
      (communicated_image_data objective32 high_res)
      (communicated_image_data objective40 high_res)
      (communicated_image_data objective42 high_res)
      (communicated_image_data objective5 colour)
      (communicated_image_data objective25 colour)
      (communicated_image_data objective20 colour)
      (communicated_image_data objective49 high_res)
      (communicated_image_data objective4 colour)
      (communicated_image_data objective46 low_res)
      (communicated_image_data objective13 colour)
      (communicated_image_data objective14 colour)
      (communicated_image_data objective12 high_res)
      (communicated_image_data objective10 high_res)
      (communicated_image_data objective27 colour)
      (communicated_image_data objective45 colour)
      (communicated_image_data objective14 low_res)
      (communicated_image_data objective28 colour)
      (communicated_image_data objective17 colour)
      (communicated_image_data objective9 low_res)
      (communicated_image_data objective50 colour)
      (communicated_image_data objective29 high_res)
      (communicated_image_data objective5 high_res)
      (communicated_image_data objective25 high_res)
      (communicated_image_data objective54 colour)
      (communicated_image_data objective52 colour)
    )
  )
  (:metric minimize (total-time))
)
