  (:goal
    (and
      (communicated_soil_data waypoint5)
      (communicated_soil_data waypoint44)
      (communicated_soil_data waypoint54)
      (communicated_soil_data waypoint29)
      (communicated_soil_data waypoint45)
      (communicated_soil_data waypoint18)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint60)
      (communicated_soil_data waypoint70)
      (communicated_soil_data waypoint0)
      (communicated_soil_data waypoint6)
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint49)
      (communicated_soil_data waypoint90)
      (communicated_soil_data waypoint30)
      (communicated_soil_data waypoint69)
      (communicated_soil_data waypoint2)
      (communicated_soil_data waypoint92)
      (communicated_soil_data waypoint34)
      (communicated_soil_data waypoint80)
      (communicated_soil_data waypoint32)
      (communicated_soil_data waypoint1)
      (communicated_soil_data waypoint58)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint59)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint95)
      (communicated_rock_data waypoint38)
      (communicated_rock_data waypoint96)
      (communicated_rock_data waypoint94)
      (communicated_rock_data waypoint58)
      (communicated_rock_data waypoint8)
      (communicated_rock_data waypoint10)
      (communicated_rock_data waypoint81)
      (communicated_rock_data waypoint97)
      (communicated_rock_data waypoint87)
      (communicated_rock_data waypoint50)
      (communicated_rock_data waypoint98)
      (communicated_rock_data waypoint51)
      (communicated_rock_data waypoint45)
      (communicated_rock_data waypoint86)
      (communicated_rock_data waypoint75)
      (communicated_rock_data waypoint85)
      (communicated_rock_data waypoint1)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint27)
      (communicated_rock_data waypoint68)
      (communicated_rock_data waypoint44)
      (communicated_rock_data waypoint23)
      (communicated_rock_data waypoint46)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint18)
      (communicated_rock_data waypoint41)
      (communicated_rock_data waypoint60)
      (communicated_rock_data waypoint76)
      (communicated_rock_data waypoint54)
      (communicated_rock_data waypoint0)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint61)
      (communicated_rock_data waypoint33)
      (communicated_rock_data waypoint48)
      (communicated_rock_data waypoint66)
      (communicated_rock_data waypoint24)
      (communicated_rock_data waypoint26)
      (communicated_rock_data waypoint89)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint47)
      (communicated_rock_data waypoint69)
      (communicated_rock_data waypoint3)
      (communicated_rock_data waypoint40)
      (communicated_image_data objective44 high_res)
      (communicated_image_data objective44 colour)
      (communicated_image_data objective18 high_res)
      (communicated_image_data objective22 colour)
      (communicated_image_data objective15 colour)
      (communicated_image_data objective5 high_res)
      (communicated_image_data objective29 high_res)
      (communicated_image_data objective31 low_res)
      (communicated_image_data objective30 high_res)
      (communicated_image_data objective9 high_res)
      (communicated_image_data objective24 high_res)
      (communicated_image_data objective6 colour)
      (communicated_image_data objective14 high_res)
      (communicated_image_data objective39 high_res)
      (communicated_image_data objective24 low_res)
      (communicated_image_data objective36 high_res)
      (communicated_image_data objective18 low_res)
      (communicated_image_data objective23 high_res)
      (communicated_image_data objective40 low_res)
      (communicated_image_data objective41 colour)
      (communicated_image_data objective6 high_res)
      (communicated_image_data objective23 low_res)
      (communicated_image_data objective31 high_res)
      (communicated_image_data objective11 colour)
      (communicated_image_data objective49 high_res)
      (communicated_image_data objective38 colour)
      (communicated_image_data objective0 high_res)
      (communicated_image_data objective0 colour)
      (communicated_image_data objective25 colour)
      (communicated_image_data objective20 colour)
      (communicated_image_data objective27 high_res)
      (communicated_image_data objective43 low_res)
      (communicated_image_data objective28 high_res)
      (communicated_image_data objective21 high_res)
      (communicated_image_data objective9 colour)
      (communicated_image_data objective16 colour)
      (communicated_image_data objective23 colour)
      (communicated_image_data objective10 high_res)
      (communicated_image_data objective45 low_res)
      (communicated_image_data objective11 high_res)
      (communicated_image_data objective15 low_res)
      (communicated_image_data objective1 colour)
      (communicated_image_data objective35 high_res)
      (communicated_image_data objective13 high_res)
      (communicated_image_data objective32 high_res)
    )
  )
  (:metric minimize (total-time))
)
