  (:goal
    (and
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint14)
      (communicated_soil_data waypoint85)
      (communicated_soil_data waypoint8)
      (communicated_soil_data waypoint70)
      (communicated_soil_data waypoint50)
      (communicated_soil_data waypoint39)
      (communicated_soil_data waypoint41)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint79)
      (communicated_soil_data waypoint13)
      (communicated_soil_data waypoint84)
      (communicated_soil_data waypoint58)
      (communicated_soil_data waypoint4)
      (communicated_soil_data waypoint90)
      (communicated_soil_data waypoint96)
      (communicated_soil_data waypoint75)
      (communicated_soil_data waypoint102)
      (communicated_soil_data waypoint95)
      (communicated_soil_data waypoint80)
      (communicated_soil_data waypoint94)
      (communicated_soil_data waypoint83)
      (communicated_soil_data waypoint76)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint27)
      (communicated_soil_data waypoint77)
      (communicated_rock_data waypoint13)
      (communicated_rock_data waypoint3)
      (communicated_rock_data waypoint78)
      (communicated_rock_data waypoint12)
      (communicated_rock_data waypoint75)
      (communicated_rock_data waypoint38)
      (communicated_rock_data waypoint15)
      (communicated_rock_data waypoint17)
      (communicated_rock_data waypoint81)
      (communicated_rock_data waypoint5)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint79)
      (communicated_rock_data waypoint86)
      (communicated_rock_data waypoint14)
      (communicated_rock_data waypoint31)
      (communicated_rock_data waypoint98)
      (communicated_rock_data waypoint26)
      (communicated_rock_data waypoint27)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint77)
      (communicated_rock_data waypoint76)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint42)
      (communicated_rock_data waypoint36)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint65)
      (communicated_rock_data waypoint19)
      (communicated_rock_data waypoint30)
      (communicated_rock_data waypoint83)
      (communicated_rock_data waypoint35)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint84)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint32)
      (communicated_rock_data waypoint59)
      (communicated_rock_data waypoint1)
      (communicated_rock_data waypoint0)
      (communicated_rock_data waypoint23)
      (communicated_rock_data waypoint97)
      (communicated_rock_data waypoint44)
      (communicated_rock_data waypoint85)
      (communicated_rock_data waypoint48)
      (communicated_image_data objective49 high_res)
      (communicated_image_data objective40 high_res)
      (communicated_image_data objective12 low_res)
      (communicated_image_data objective14 low_res)
      (communicated_image_data objective45 colour)
      (communicated_image_data objective18 low_res)
      (communicated_image_data objective24 low_res)
      (communicated_image_data objective20 low_res)
      (communicated_image_data objective45 low_res)
      (communicated_image_data objective19 low_res)
      (communicated_image_data objective3 low_res)
      (communicated_image_data objective48 high_res)
      (communicated_image_data objective3 colour)
      (communicated_image_data objective12 high_res)
      (communicated_image_data objective15 low_res)
      (communicated_image_data objective18 colour)
      (communicated_image_data objective13 low_res)
      (communicated_image_data objective40 low_res)
      (communicated_image_data objective32 high_res)
      (communicated_image_data objective29 colour)
      (communicated_image_data objective26 high_res)
      (communicated_image_data objective23 low_res)
      (communicated_image_data objective15 high_res)
      (communicated_image_data objective46 low_res)
    )
  )
  (:metric minimize (total-time))
)
