  (:goal
    (and
      (communicated_soil_data waypoint36)
      (communicated_soil_data waypoint24)
      (communicated_soil_data waypoint26)
      (communicated_soil_data waypoint54)
      (communicated_soil_data waypoint74)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint28)
      (communicated_soil_data waypoint44)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint85)
      (communicated_soil_data waypoint90)
      (communicated_soil_data waypoint41)
      (communicated_soil_data waypoint92)
      (communicated_soil_data waypoint51)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint5)
      (communicated_soil_data waypoint18)
      (communicated_soil_data waypoint72)
      (communicated_soil_data waypoint95)
      (communicated_soil_data waypoint57)
      (communicated_soil_data waypoint4)
      (communicated_soil_data waypoint69)
      (communicated_soil_data waypoint73)
      (communicated_soil_data waypoint79)
      (communicated_soil_data waypoint96)
      (communicated_soil_data waypoint91)
      (communicated_soil_data waypoint46)
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint50)
      (communicated_soil_data waypoint33)
      (communicated_soil_data waypoint81)
      (communicated_soil_data waypoint10)
      (communicated_soil_data waypoint59)
      (communicated_soil_data waypoint66)
      (communicated_soil_data waypoint87)
      (communicated_soil_data waypoint62)
      (communicated_soil_data waypoint56)
      (communicated_soil_data waypoint22)
      (communicated_soil_data waypoint20)
      (communicated_soil_data waypoint94)
      (communicated_soil_data waypoint1)
      (communicated_soil_data waypoint12)
      (communicated_soil_data waypoint88)
      (communicated_soil_data waypoint61)
      (communicated_soil_data waypoint60)
      (communicated_soil_data waypoint89)
      (communicated_soil_data waypoint99)
      (communicated_soil_data waypoint68)
      (communicated_soil_data waypoint37)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint0)
      (communicated_rock_data waypoint68)
      (communicated_rock_data waypoint17)
      (communicated_rock_data waypoint35)
      (communicated_rock_data waypoint4)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint66)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint98)
      (communicated_rock_data waypoint36)
      (communicated_rock_data waypoint49)
      (communicated_rock_data waypoint81)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint48)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint3)
      (communicated_rock_data waypoint34)
      (communicated_rock_data waypoint60)
      (communicated_rock_data waypoint91)
      (communicated_rock_data waypoint6)
      (communicated_rock_data waypoint7)
      (communicated_rock_data waypoint54)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint25)
      (communicated_rock_data waypoint67)
      (communicated_rock_data waypoint2)
      (communicated_rock_data waypoint32)
      (communicated_rock_data waypoint86)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint89)
      (communicated_rock_data waypoint10)
      (communicated_rock_data waypoint92)
      (communicated_rock_data waypoint58)
      (communicated_rock_data waypoint87)
      (communicated_rock_data waypoint18)
      (communicated_rock_data waypoint59)
      (communicated_rock_data waypoint84)
      (communicated_rock_data waypoint14)
      (communicated_rock_data waypoint47)
      (communicated_rock_data waypoint97)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint56)
      (communicated_rock_data waypoint33)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint78)
      (communicated_rock_data waypoint64)
      (communicated_rock_data waypoint75)
      (communicated_rock_data waypoint43)
      (communicated_rock_data waypoint88)
      (communicated_rock_data waypoint51)
      (communicated_rock_data waypoint12)
      (communicated_rock_data waypoint55)
      (communicated_image_data objective27 low_res)
      (communicated_image_data objective25 high_res)
      (communicated_image_data objective44 high_res)
      (communicated_image_data objective22 high_res)
      (communicated_image_data objective23 high_res)
      (communicated_image_data objective15 low_res)
      (communicated_image_data objective5 high_res)
      (communicated_image_data objective28 low_res)
      (communicated_image_data objective47 low_res)
      (communicated_image_data objective43 high_res)
      (communicated_image_data objective1 low_res)
      (communicated_image_data objective4 low_res)
      (communicated_image_data objective44 colour)
      (communicated_image_data objective8 high_res)
      (communicated_image_data objective24 low_res)
      (communicated_image_data objective21 high_res)
      (communicated_image_data objective11 high_res)
      (communicated_image_data objective21 low_res)
      (communicated_image_data objective31 low_res)
      (communicated_image_data objective19 low_res)
      (communicated_image_data objective12 low_res)
      (communicated_image_data objective44 low_res)
      (communicated_image_data objective5 low_res)
      (communicated_image_data objective31 high_res)
      (communicated_image_data objective33 high_res)
      (communicated_image_data objective45 low_res)
      (communicated_image_data objective45 high_res)
      (communicated_image_data objective22 low_res)
      (communicated_image_data objective24 high_res)
      (communicated_image_data objective39 low_res)
      (communicated_image_data objective46 high_res)
      (communicated_image_data objective30 high_res)
      (communicated_image_data objective48 low_res)
      (communicated_image_data objective36 high_res)
      (communicated_image_data objective12 high_res)
      (communicated_image_data objective46 low_res)
      (communicated_image_data objective49 high_res)
      (communicated_image_data objective16 low_res)
      (communicated_image_data objective11 low_res)
      (communicated_image_data objective40 high_res)
      (communicated_image_data objective43 low_res)
      (communicated_image_data objective10 high_res)
      (communicated_image_data objective14 low_res)
      (communicated_image_data objective2 low_res)
      (communicated_image_data objective15 high_res)
	  )
  )
  (:metric minimize (total-time))
)
