  (:goal
    (and
      (communicated_soil_data waypoint25)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint93)
      (communicated_soil_data waypoint61)
      (communicated_soil_data waypoint100)
      (communicated_soil_data waypoint30)
      (communicated_soil_data waypoint74)
      (communicated_soil_data waypoint63)
      (communicated_soil_data waypoint46)
      (communicated_soil_data waypoint40)
      (communicated_soil_data waypoint68)
      (communicated_soil_data waypoint0)
      (communicated_soil_data waypoint66)
      (communicated_soil_data waypoint92)
      (communicated_soil_data waypoint76)
      (communicated_soil_data waypoint56)
      (communicated_soil_data waypoint26)
      (communicated_soil_data waypoint18)
      (communicated_soil_data waypoint38)
      (communicated_soil_data waypoint59)
      (communicated_soil_data waypoint69)
      (communicated_soil_data waypoint28)
      (communicated_soil_data waypoint85)
      (communicated_soil_data waypoint44)
      (communicated_soil_data waypoint60)
      (communicated_soil_data waypoint103)
      (communicated_soil_data waypoint89)
      (communicated_soil_data waypoint50)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint14)
      (communicated_soil_data waypoint104)
      (communicated_soil_data waypoint8)
      (communicated_soil_data waypoint29)
      (communicated_soil_data waypoint32)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint57)
      (communicated_soil_data waypoint20)
      (communicated_soil_data waypoint71)
      (communicated_soil_data waypoint13)
      (communicated_soil_data waypoint5)
      (communicated_soil_data waypoint37)
      (communicated_soil_data waypoint91)
      (communicated_soil_data waypoint73)
      (communicated_rock_data waypoint86)
      (communicated_rock_data waypoint1)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint44)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint3)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint25)
      (communicated_rock_data waypoint14)
      (communicated_rock_data waypoint74)
      (communicated_rock_data waypoint51)
      (communicated_rock_data waypoint93)
      (communicated_rock_data waypoint100)
      (communicated_rock_data waypoint13)
      (communicated_rock_data waypoint15)
      (communicated_rock_data waypoint56)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint26)
      (communicated_rock_data waypoint102)
      (communicated_rock_data waypoint55)
      (communicated_rock_data waypoint33)
      (communicated_rock_data waypoint65)
      (communicated_rock_data waypoint58)
      (communicated_rock_data waypoint38)
      (communicated_rock_data waypoint54)
      (communicated_rock_data waypoint68)
      (communicated_rock_data waypoint9)
      (communicated_rock_data waypoint46)
      (communicated_rock_data waypoint50)
      (communicated_rock_data waypoint18)
      (communicated_rock_data waypoint4)
      (communicated_rock_data waypoint101)
      (communicated_rock_data waypoint94)
      (communicated_rock_data waypoint10)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint83)
      (communicated_rock_data waypoint5)
      (communicated_rock_data waypoint23)
      (communicated_rock_data waypoint52)
      (communicated_rock_data waypoint8)
      (communicated_rock_data waypoint96)
      (communicated_rock_data waypoint6)
      (communicated_rock_data waypoint45)
      (communicated_rock_data waypoint75)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint67)
      (communicated_rock_data waypoint40)
      (communicated_rock_data waypoint17)
      (communicated_rock_data waypoint91)
      (communicated_rock_data waypoint84)
      (communicated_rock_data waypoint32)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint47)
      (communicated_rock_data waypoint69)
      (communicated_image_data objective18 low_res)
      (communicated_image_data objective26 high_res)
      (communicated_image_data objective8 high_res)
      (communicated_image_data objective33 low_res)
      (communicated_image_data objective52 high_res)
      (communicated_image_data objective20 low_res)
      (communicated_image_data objective39 colour)
      (communicated_image_data objective46 high_res)
      (communicated_image_data objective25 colour)
      (communicated_image_data objective21 low_res)
      (communicated_image_data objective45 low_res)
      (communicated_image_data objective21 colour)
      (communicated_image_data objective44 high_res)
      (communicated_image_data objective7 high_res)
      (communicated_image_data objective46 colour)
      (communicated_image_data objective25 low_res)
      (communicated_image_data objective16 colour)
      (communicated_image_data objective51 low_res)
    )
  )
  (:metric minimize (total-time))
)
