  (:goal
    (and
      (communicated_soil_data waypoint56)
      (communicated_soil_data waypoint1)
      (communicated_soil_data waypoint35)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint0)
      (communicated_soil_data waypoint96)
      (communicated_soil_data waypoint7)
      (communicated_soil_data waypoint68)
      (communicated_soil_data waypoint8)
      (communicated_soil_data waypoint77)
      (communicated_soil_data waypoint91)
      (communicated_soil_data waypoint82)
      (communicated_soil_data waypoint87)
      (communicated_soil_data waypoint54)
      (communicated_soil_data waypoint32)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint33)
      (communicated_soil_data waypoint83)
      (communicated_soil_data waypoint16)
      (communicated_soil_data waypoint61)
      (communicated_soil_data waypoint93)
      (communicated_soil_data waypoint79)
      (communicated_soil_data waypoint75)
      (communicated_soil_data waypoint44)
      (communicated_soil_data waypoint80)
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint76)
      (communicated_soil_data waypoint72)
      (communicated_soil_data waypoint55)
      (communicated_soil_data waypoint25)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint46)
      (communicated_soil_data waypoint40)
      (communicated_soil_data waypoint24)
      (communicated_soil_data waypoint4)
      (communicated_soil_data waypoint51)
      (communicated_soil_data waypoint99)
      (communicated_soil_data waypoint58)
      (communicated_soil_data waypoint74)
      (communicated_soil_data waypoint84)
      (communicated_soil_data waypoint89)
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint71)
      (communicated_soil_data waypoint43)
      (communicated_soil_data waypoint48)
      (communicated_soil_data waypoint29)
      (communicated_soil_data waypoint36)
      (communicated_soil_data waypoint81)
      (communicated_soil_data waypoint18)
      (communicated_soil_data waypoint53)
      (communicated_soil_data waypoint90)
      (communicated_soil_data waypoint31)
      (communicated_soil_data waypoint70)
      (communicated_rock_data waypoint9)
      (communicated_rock_data waypoint59)
      (communicated_rock_data waypoint23)
      (communicated_rock_data waypoint79)
      (communicated_rock_data waypoint73)
      (communicated_rock_data waypoint47)
      (communicated_rock_data waypoint63)
      (communicated_rock_data waypoint35)
      (communicated_rock_data waypoint18)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint52)
      (communicated_rock_data waypoint67)
      (communicated_rock_data waypoint27)
      (communicated_rock_data waypoint46)
      (communicated_rock_data waypoint64)
      (communicated_rock_data waypoint15)
      (communicated_rock_data waypoint4)
      (communicated_rock_data waypoint97)
      (communicated_rock_data waypoint57)
      (communicated_rock_data waypoint74)
      (communicated_rock_data waypoint17)
      (communicated_rock_data waypoint78)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint71)
      (communicated_rock_data waypoint91)
      (communicated_rock_data waypoint2)
      (communicated_rock_data waypoint10)
      (communicated_rock_data waypoint98)
      (communicated_rock_data waypoint19)
      (communicated_rock_data waypoint25)
      (communicated_image_data objective11 high_res)
      (communicated_image_data objective40 low_res)
      (communicated_image_data objective11 low_res)
      (communicated_image_data objective27 high_res)
      (communicated_image_data objective40 colour)
      (communicated_image_data objective12 colour)
      (communicated_image_data objective21 colour)
      (communicated_image_data objective30 colour)
      (communicated_image_data objective27 colour)
      (communicated_image_data objective29 low_res)
      (communicated_image_data objective47 high_res)
      (communicated_image_data objective2 low_res)
      (communicated_image_data objective42 colour)
      (communicated_image_data objective2 colour)
      (communicated_image_data objective32 low_res)
      (communicated_image_data objective37 high_res)
      (communicated_image_data objective27 low_res)
      (communicated_image_data objective43 high_res)
      (communicated_image_data objective6 low_res)
      (communicated_image_data objective6 colour)
      (communicated_image_data objective16 colour)
      (communicated_image_data objective25 colour)
      (communicated_image_data objective8 low_res)
      (communicated_image_data objective26 low_res)
      (communicated_image_data objective0 low_res)
    )
  )
  (:metric minimize (total-time))
)
