  (:goal 
    (and
      (communicated_soil_data waypoint52)
      (communicated_soil_data waypoint47)
      (communicated_soil_data waypoint9)
      (communicated_soil_data waypoint91)
      (communicated_soil_data waypoint13)
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint16)
      (communicated_soil_data waypoint12)
      (communicated_soil_data waypoint39)
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint58)
      (communicated_soil_data waypoint48)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint27)
      (communicated_soil_data waypoint4)
      (communicated_soil_data waypoint33)
      (communicated_soil_data waypoint5)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint50)
      (communicated_soil_data waypoint18)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint61)
      (communicated_rock_data waypoint63)
      (communicated_rock_data waypoint18)
      (communicated_rock_data waypoint89)
      (communicated_rock_data waypoint33)
      (communicated_rock_data waypoint67)
      (communicated_rock_data waypoint38)
      (communicated_rock_data waypoint35)
      (communicated_rock_data waypoint99)
      (communicated_rock_data waypoint88)
      (communicated_rock_data waypoint40)
      (communicated_rock_data waypoint31)
      (communicated_rock_data waypoint94)
      (communicated_rock_data waypoint44)
      (communicated_rock_data waypoint48)
      (communicated_rock_data waypoint60)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint5)
      (communicated_rock_data waypoint34)
      (communicated_rock_data waypoint92)
      (communicated_rock_data waypoint75)
      (communicated_image_data objective6 high_res)
      (communicated_image_data objective32 low_res)
      (communicated_image_data objective44 high_res)
      (communicated_image_data objective33 low_res)
      (communicated_image_data objective26 colour)
      (communicated_image_data objective38 low_res)
      (communicated_image_data objective9 low_res)
      (communicated_image_data objective43 colour)
      (communicated_image_data objective9 high_res)
      (communicated_image_data objective16 low_res)
      (communicated_image_data objective28 high_res)
      (communicated_image_data objective48 high_res)
      (communicated_image_data objective10 colour)
      (communicated_image_data objective1 low_res)
      (communicated_image_data objective34 low_res)
      (communicated_image_data objective19 low_res)
      (communicated_image_data objective36 colour)
      (communicated_image_data objective27 high_res)
      (communicated_image_data objective1 high_res)
      (communicated_image_data objective24 low_res)
      (communicated_image_data objective28 colour)
      (communicated_image_data objective11 low_res)
      (communicated_image_data objective19 high_res)
      (communicated_image_data objective36 low_res)
      (communicated_image_data objective23 low_res)
      (communicated_image_data objective49 high_res)
      (communicated_image_data objective39 low_res)
      (communicated_image_data objective42 high_res)
      (communicated_image_data objective22 low_res)
      (communicated_image_data objective49 low_res)
      (communicated_image_data objective26 high_res)
      (communicated_image_data objective46 low_res)
      (communicated_image_data objective11 high_res)
      (communicated_image_data objective41 high_res)
      (communicated_image_data objective40 low_res)
      (communicated_image_data objective18 high_res)
      (communicated_image_data objective40 high_res)
      (communicated_image_data objective4 colour)
      (communicated_image_data objective23 high_res)
      (communicated_image_data objective31 high_res)
      (communicated_image_data objective9 colour)
      (communicated_image_data objective4 high_res)
      (communicated_image_data objective43 high_res)
      (communicated_image_data objective5 high_res)
      (communicated_image_data objective34 high_res)
      (communicated_image_data objective13 high_res)
      (communicated_image_data objective27 low_res)
      (communicated_image_data objective33 high_res)
      (communicated_image_data objective13 colour)
    )
  )
  (:metric minimize (total-time))
)
