  (:goal
    (and
      (communicated_soil_data waypoint64)
      (communicated_soil_data waypoint65)
      (communicated_soil_data waypoint9)
      (communicated_soil_data waypoint36)
      (communicated_soil_data waypoint37)
      (communicated_soil_data waypoint26)
      (communicated_soil_data waypoint104)
      (communicated_soil_data waypoint102)
      (communicated_soil_data waypoint53)
      (communicated_soil_data waypoint14)
      (communicated_soil_data waypoint45)
      (communicated_soil_data waypoint95)
      (communicated_soil_data waypoint15)
      (communicated_soil_data waypoint20)
      (communicated_soil_data waypoint32)
      (communicated_soil_data waypoint96)
      (communicated_soil_data waypoint81)
      (communicated_soil_data waypoint72)
      (communicated_soil_data waypoint10)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint60)
      (communicated_soil_data waypoint52)
      (communicated_soil_data waypoint103)
      (communicated_soil_data waypoint11)
      (communicated_soil_data waypoint8)
      (communicated_soil_data waypoint63)
      (communicated_soil_data waypoint27)
      (communicated_soil_data waypoint86)
      (communicated_soil_data waypoint48)
      (communicated_soil_data waypoint46)
      (communicated_rock_data waypoint11)
      (communicated_rock_data waypoint96)
      (communicated_rock_data waypoint55)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint82)
      (communicated_rock_data waypoint62)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint60)
      (communicated_rock_data waypoint40)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint27)
      (communicated_rock_data waypoint46)
      (communicated_rock_data waypoint83)
      (communicated_rock_data waypoint80)
      (communicated_rock_data waypoint99)
      (communicated_rock_data waypoint81)
      (communicated_rock_data waypoint87)
      (communicated_rock_data waypoint101)
      (communicated_rock_data waypoint10)
      (communicated_rock_data waypoint12)
      (communicated_rock_data waypoint34)
      (communicated_rock_data waypoint7)
      (communicated_rock_data waypoint77)
      (communicated_rock_data waypoint41)
      (communicated_rock_data waypoint13)
      (communicated_rock_data waypoint69)
      (communicated_rock_data waypoint100)
      (communicated_rock_data waypoint68)
      (communicated_rock_data waypoint31)
      (communicated_rock_data waypoint95)
      (communicated_rock_data waypoint58)
      (communicated_rock_data waypoint15)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint39)
      (communicated_rock_data waypoint54)
      (communicated_rock_data waypoint0)
      (communicated_rock_data waypoint52)
      (communicated_rock_data waypoint61)
      (communicated_rock_data waypoint9)
      (communicated_rock_data waypoint23)
      (communicated_image_data objective1 colour)
      (communicated_image_data objective10 high_res)
      (communicated_image_data objective24 low_res)
      (communicated_image_data objective30 low_res)
      (communicated_image_data objective17 low_res)
      (communicated_image_data objective43 high_res)
      (communicated_image_data objective7 colour)
      (communicated_image_data objective49 low_res)
      (communicated_image_data objective46 low_res)
      (communicated_image_data objective47 colour)
      (communicated_image_data objective9 low_res)
      (communicated_image_data objective34 colour)
      (communicated_image_data objective39 low_res)
      (communicated_image_data objective7 high_res)
      (communicated_image_data objective29 colour)
      (communicated_image_data objective16 low_res)
      (communicated_image_data objective20 colour)
      (communicated_image_data objective43 colour)
      (communicated_image_data objective5 high_res)
      (communicated_image_data objective48 high_res)
      (communicated_image_data objective45 high_res)
      (communicated_image_data objective30 high_res)
      (communicated_image_data objective3 low_res)
      (communicated_image_data objective42 low_res)
      (communicated_image_data objective9 high_res)
      (communicated_image_data objective20 high_res)
      (communicated_image_data objective27 high_res)
      (communicated_image_data objective46 high_res)
      (communicated_image_data objective1 high_res)
      (communicated_image_data objective35 high_res)
      (communicated_image_data objective15 high_res)
      (communicated_image_data objective4 high_res)
      (communicated_image_data objective8 low_res)
      (communicated_image_data objective34 low_res)
      (communicated_image_data objective16 colour)
      (communicated_image_data objective38 high_res)
      (communicated_image_data objective14 high_res)
      (communicated_image_data objective41 low_res)
      (communicated_image_data objective41 colour)
      (communicated_image_data objective22 colour)
      (communicated_image_data objective0 colour)
      (communicated_image_data objective47 low_res)
      (communicated_image_data objective15 colour)
      (communicated_image_data objective43 low_res)
      (communicated_image_data objective32 low_res)
      (communicated_image_data objective50 high_res)
      (communicated_image_data objective48 low_res)
      (communicated_image_data objective19 high_res)
      (communicated_image_data objective1 low_res)
    )
  )
  (:metric minimize (total-time))
)
