  (equipped_for_rock_analysis rover0)

  (equipped_for_soil_analysis rover1)
  (equipped_for_imaging rover1)
  (on_board camera0 rover1)
  (calibration_target camera0 objective41)
  (supports camera0 low_res)
  (supports camera0 high_res)

  (equipped_for_soil_analysis rover2)
  (equipped_for_rock_analysis rover2)

  (equipped_for_imaging rover3)
  (on_board camera1 rover3)
  (calibration_target camera1 objective34)
  (supports camera1 low_res)

  (equipped_for_rock_analysis rover4)
  (equipped_for_imaging rover4)
  (on_board camera2 rover4)
  (calibration_target camera2 objective34)
  (supports camera2 colour)
  (supports camera2 high_res)

  (equipped_for_imaging rover5)
  (on_board camera3 rover5)
  (calibration_target camera3 objective11)
  (supports camera3 low_res)
  (supports camera3 high_res)

  (equipped_for_soil_analysis rover6)
  (equipped_for_imaging rover6)
  (on_board camera4 rover6)
  (calibration_target camera4 objective45)
  (supports camera4 colour)
  (supports camera4 low_res)

  (equipped_for_soil_analysis rover7)
  (equipped_for_rock_analysis rover7)
  (equipped_for_imaging rover7)
  (on_board camera5 rover7)
  (calibration_target camera5 objective48)
  (supports camera5 low_res)

  (equipped_for_soil_analysis rover8)

  (equipped_for_rock_analysis rover9)
  (equipped_for_imaging rover9)
  (on_board camera6 rover9)
  (calibration_target camera6 objective35)
  (supports camera6 colour)
  (supports camera6 low_res)
