  (:goal
    (and
      (communicated_soil_data waypoint95)
      (communicated_soil_data waypoint2)
      (communicated_soil_data waypoint28)
      (communicated_soil_data waypoint23)
      (communicated_soil_data waypoint29)
      (communicated_soil_data waypoint91)
      (communicated_soil_data waypoint42)
      (communicated_soil_data waypoint43)
      (communicated_soil_data waypoint78)
      (communicated_soil_data waypoint57)
      (communicated_soil_data waypoint10)
      (communicated_soil_data waypoint87)
      (communicated_soil_data waypoint80)
      (communicated_soil_data waypoint52)
      (communicated_soil_data waypoint67)
      (communicated_soil_data waypoint16)
      (communicated_soil_data waypoint97)
      (communicated_soil_data waypoint90)
      (communicated_soil_data waypoint19)
      (communicated_soil_data waypoint79)
      (communicated_soil_data waypoint14)
      (communicated_soil_data waypoint9)
      (communicated_soil_data waypoint74)
      (communicated_soil_data waypoint47)
      (communicated_soil_data waypoint82)
      (communicated_soil_data waypoint37)
      (communicated_soil_data waypoint84)
      (communicated_soil_data waypoint66)
      (communicated_soil_data waypoint6)
      (communicated_soil_data waypoint54)
      (communicated_soil_data waypoint49)
      (communicated_soil_data waypoint98)
      (communicated_soil_data waypoint101)
      (communicated_soil_data waypoint35)
      (communicated_soil_data waypoint77)
      (communicated_soil_data waypoint56)
      (communicated_soil_data waypoint76)
      (communicated_soil_data waypoint71)
      (communicated_soil_data waypoint33)
      (communicated_soil_data waypoint41)
      (communicated_soil_data waypoint75)
      (communicated_soil_data waypoint27)
      (communicated_soil_data waypoint25)
      (communicated_soil_data waypoint46)
      (communicated_soil_data waypoint81)
      (communicated_soil_data waypoint83)
      (communicated_soil_data waypoint94)
      (communicated_soil_data waypoint88)
      (communicated_soil_data waypoint4)
      (communicated_soil_data waypoint13)
      (communicated_soil_data waypoint92)
      (communicated_soil_data waypoint31)
      (communicated_soil_data waypoint53)
      (communicated_soil_data waypoint65)
      (communicated_soil_data waypoint102)
      (communicated_soil_data waypoint30)
      (communicated_rock_data waypoint35)
      (communicated_rock_data waypoint0)
      (communicated_rock_data waypoint42)
      (communicated_rock_data waypoint104)
      (communicated_rock_data waypoint63)
      (communicated_rock_data waypoint22)
      (communicated_rock_data waypoint32)
      (communicated_rock_data waypoint28)
      (communicated_rock_data waypoint11)
      (communicated_rock_data waypoint64)
      (communicated_rock_data waypoint26)
      (communicated_rock_data waypoint19)
      (communicated_rock_data waypoint12)
      (communicated_rock_data waypoint8)
      (communicated_rock_data waypoint96)
      (communicated_rock_data waypoint52)
      (communicated_rock_data waypoint50)
      (communicated_rock_data waypoint44)
      (communicated_rock_data waypoint99)
      (communicated_rock_data waypoint79)
      (communicated_rock_data waypoint84)
      (communicated_rock_data waypoint21)
      (communicated_rock_data waypoint86)
      (communicated_rock_data waypoint53)
      (communicated_rock_data waypoint90)
      (communicated_rock_data waypoint30)
      (communicated_rock_data waypoint46)
      (communicated_rock_data waypoint2)
      (communicated_rock_data waypoint34)
      (communicated_rock_data waypoint9)
      (communicated_rock_data waypoint56)
      (communicated_rock_data waypoint58)
      (communicated_rock_data waypoint59)
      (communicated_rock_data waypoint101)
      (communicated_rock_data waypoint31)
      (communicated_rock_data waypoint70)
      (communicated_rock_data waypoint36)
      (communicated_image_data objective7 low_res)
      (communicated_image_data objective5 low_res)
      (communicated_image_data objective4 colour)
      (communicated_image_data objective12 colour)
      (communicated_image_data objective45 colour)
      (communicated_image_data objective13 low_res)
      (communicated_image_data objective54 high_res)
      (communicated_image_data objective41 high_res)
      (communicated_image_data objective8 colour)
      (communicated_image_data objective21 colour)
      (communicated_image_data objective28 colour)
      (communicated_image_data objective4 low_res)
      (communicated_image_data objective9 high_res)
      (communicated_image_data objective13 colour)
      (communicated_image_data objective35 colour)
      (communicated_image_data objective39 colour)
      (communicated_image_data objective24 high_res)
      (communicated_image_data objective9 low_res)
      (communicated_image_data objective52 high_res)
      (communicated_image_data objective36 colour)
      (communicated_image_data objective54 colour)
      (communicated_image_data objective10 colour)
      (communicated_image_data objective23 high_res)
      (communicated_image_data objective17 colour)
    )
  )
  (:metric minimize (total-time))
)
