  (equipped_for_rock_analysis rover0)
  (equipped_for_imaging rover0)
  (on_board camera0 rover0)
  (calibration_target camera0 objective41)
  (supports camera0 high_res)

  (equipped_for_imaging rover1)
  (on_board camera1 rover1)
  (calibration_target camera1 objective34)
  (supports camera1 low_res)

  (equipped_for_rock_analysis rover2)
  (equipped_for_imaging rover2)
  (on_board camera2 rover2)
  (calibration_target camera2 objective34)
  (supports camera2 colour)

  (equipped_for_imaging rover3)
  (on_board camera3 rover3)
  (calibration_target camera3 objective11)
  (supports camera3 low_res)
  (supports camera3 colour)
  (supports camera3 high_res)

  (equipped_for_soil_analysis rover4)
  (equipped_for_imaging rover4)
  (on_board camera4 rover4)
  (calibration_target camera4 objective45)
  (supports camera4 colour)
  (supports camera4 low_res)

  (equipped_for_soil_analysis rover5)
  (equipped_for_imaging rover5)
  (on_board camera5 rover5)
  (calibration_target camera5 objective48)
  (supports camera5 low_res)
  (supports camera5 colour)

  (equipped_for_soil_analysis rover6)
  (equipped_for_imaging rover6)
  (on_board camera6 rover6)
  (calibration_target camera6 objective35)
  (supports camera6 colour)

  (equipped_for_soil_analysis rover7)
  (equipped_for_imaging rover7)
  (on_board camera7 rover7)
  (calibration_target camera7 objective17)
  (supports camera7 low_res)

  (equipped_for_rock_analysis rover8)

  (equipped_for_imaging rover9)
  (on_board camera8 rover9)
  (calibration_target camera8 objective37)
  (supports camera8 high_res)
